name: ğŸŒ Scrape Wiki
on:
  push:
    branches:
      - main
# on:
#   schedule:
#     - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ğŸŒ Scrape Wiki
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: ğŸŒ Scrape Wiki
        run: deno run --allow-net --allow-read --allow-write ./scripts/scrape-wiki.ts

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "bot: genres changed"
